# Mapeos de nombres (mínimos). Amplía según necesites.
# Clave: nombre en Football-Data; Valor: nombre en Understat
Arsenal: Arsenal
Chelsea: Chelsea
Manchester City: Manchester City
Manchester City FC: Manchester City
Man City: Manchester City
Man United: Manchester United
Manchester United: Manchester United
Manchester United FC: Manchester United
Liverpool: Liverpool
Liverpool FC: Liverpool
Tottenham: Tottenham
Tottenham Hotspur: Tottenham
Newcastle: Newcastle United
Newcastle United FC: Newcastle United
Aston Villa: Aston Villa
Aston Villa FC: Aston Villa
West Ham: West Ham
West Ham United FC: West Ham
Leeds: Leeds United
Leeds United FC: Leeds United
Brighton: Brighton
Brighton & Hove Albion: Brighton
Brentford: Brentford
Brentford FC: Brentford
Sunderland: Sunderland
Sunderland AFC: Sunderland
Fulham: Fulham
Fulham FC: Fulham
