# Logos de equipos de fútbol
# URL de logos de equipos principales

premier_league:
  Manchester United: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-United-Logo.png"
  Manchester City: "https://logos-world.net/wp-content/uploads/2020/06/Manchester-City-Logo.png"
  Liverpool: "https://logos-world.net/wp-content/uploads/2020/06/Liverpool-Logo.png"
  Chelsea: "https://logos-world.net/wp-content/uploads/2020/06/Chelsea-Logo.png"
  Arsenal: "https://logos-world.net/wp-content/uploads/2020/06/Arsenal-Logo.png"
  Tottenham: "https://logos-world.net/wp-content/uploads/2020/06/Tottenham-Logo.png"
  Newcastle: "https://logos-world.net/wp-content/uploads/2020/06/Newcastle-United-Logo.png"
  West Ham: "https://logos-world.net/wp-content/uploads/2020/06/West-Ham-Logo.png"
  Leeds: "https://logos-world.net/wp-content/uploads/2020/06/Leeds-United-Logo.png"
  Brighton: "https://logos-world.net/wp-content/uploads/2020/06/Brighton-Logo.png"
  Brentford: "https://logos-world.net/wp-content/uploads/2020/06/Brentford-Logo.png"
  Sunderland: "https://logos-world.net/wp-content/uploads/2020/06/Sunderland-Logo.png"
  Fulham: "https://logos-world.net/wp-content/uploads/2020/06/Fulham-Logo.png"
  Everton: "https://logos-world.net/wp-content/uploads/2020/06/Everton-Logo.png"
  Aston Villa: "https://logos-world.net/wp-content/uploads/2020/06/Aston-Villa-Logo.png"
  Crystal Palace: "https://logos-world.net/wp-content/uploads/2020/06/Crystal-Palace-Logo.png"
  Leicester: "https://logos-world.net/wp-content/uploads/2020/06/Leicester-City-Logo.png"
  Southampton: "https://logos-world.net/wp-content/uploads/2020/06/Southampton-Logo.png"
  Wolves: "https://logos-world.net/wp-content/uploads/2020/06/Wolves-Logo.png"
  Burnley: "https://logos-world.net/wp-content/uploads/2020/06/Burnley-Logo.png"
  Norwich: "https://logos-world.net/wp-content/uploads/2020/06/Norwich-Logo.png"
  Watford: "https://logos-world.net/wp-content/uploads/2020/06/Watford-Logo.png"
  Nottingham Forest: "https://logos-world.net/wp-content/uploads/2020/06/Nottingham-Forest-Logo.png"
  Sheffield United: "https://logos-world.net/wp-content/uploads/2020/06/Sheffield-United-Logo.png"
  Luton Town: "https://logos-world.net/wp-content/uploads/2020/06/Luton-Town-Logo.png"
  Bournemouth: "https://logos-world.net/wp-content/uploads/2020/06/Bournemouth-Logo.png"
  Ipswich: "https://logos-world.net/wp-content/uploads/2020/06/Ipswich-Town-Logo.png"
  Sheffield Wednesday: "https://logos-world.net/wp-content/uploads/2020/06/Sheffield-Wednesday-Logo.png"
  Hull City: "https://logos-world.net/wp-content/uploads/2020/06/Hull-City-Logo.png"
  Coventry: "https://logos-world.net/wp-content/uploads/2020/06/Coventry-City-Logo.png"
  Cardiff: "https://logos-world.net/wp-content/uploads/2020/06/Cardiff-City-Logo.png"
  Swansea: "https://logos-world.net/wp-content/uploads/2020/06/Swansea-City-Logo.png"
  Bristol City: "https://logos-world.net/wp-content/uploads/2020/06/Bristol-City-Logo.png"
  Middlesbrough: "https://logos-world.net/wp-content/uploads/2020/06/Middlesbrough-Logo.png"
  Stoke City: "https://logos-world.net/wp-content/uploads/2020/06/Stoke-City-Logo.png"
  Preston: "https://logos-world.net/wp-content/uploads/2020/06/Preston-North-End-Logo.png"
  QPR: "https://logos-world.net/wp-content/uploads/2020/06/Queens-Park-Rangers-Logo.png"
  Millwall: "https://logos-world.net/wp-content/uploads/2020/06/Millwall-Logo.png"
  Blackburn: "https://logos-world.net/wp-content/uploads/2020/06/Blackburn-Rovers-Logo.png"
  Huddersfield: "https://logos-world.net/wp-content/uploads/2020/06/Huddersfield-Town-Logo.png"
  Birmingham: "https://logos-world.net/wp-content/uploads/2020/06/Birmingham-City-Logo.png"
  Derby: "https://logos-world.net/wp-content/uploads/2020/06/Derby-County-Logo.png"
  Reading: "https://logos-world.net/wp-content/uploads/2020/06/Reading-Logo.png"
  Wigan: "https://logos-world.net/wp-content/uploads/2020/06/Wigan-Athletic-Logo.png"
  Rotherham: "https://logos-world.net/wp-content/uploads/2020/06/Rotherham-United-Logo.png"
  Plymouth: "https://logos-world.net/wp-content/uploads/2020/06/Plymouth-Argyle-Logo.png"
  Portsmouth: "https://logos-world.net/wp-content/uploads/2020/06/Portsmouth-Logo.png"
  Oxford: "https://logos-world.net/wp-content/uploads/2020/06/Oxford-United-Logo.png"
  Blackpool: "https://logos-world.net/wp-content/uploads/2020/06/Blackpool-Logo.png"
  Charlton: "https://logos-world.net/wp-content/uploads/2020/06/Charlton-Athletic-Logo.png"
  Peterborough: "https://logos-world.net/wp-content/uploads/2020/06/Peterborough-United-Logo.png"
  Wycombe: "https://logos-world.net/wp-content/uploads/2020/06/Wycombe-Wanderers-Logo.png"
  Fleetwood: "https://logos-world.net/wp-content/uploads/2020/06/Fleetwood-Town-Logo.png"
  Shrewsbury: "https://logos-world.net/wp-content/uploads/2020/06/Shrewsbury-Town-Logo.png"
  Lincoln: "https://logos-world.net/wp-content/uploads/2020/06/Lincoln-City-Logo.png"
  Exeter: "https://logos-world.net/wp-content/uploads/2020/06/Exeter-City-Logo.png"
  Cambridge: "https://logos-world.net/wp-content/uploads/2020/06/Cambridge-United-Logo.png"
  Burton: "https://logos-world.net/wp-content/uploads/2020/06/Burton-Albion-Logo.png"
  Port Vale: "https://logos-world.net/wp-content/uploads/2020/06/Port-Vale-Logo.png"
  Stevenage: "https://logos-world.net/wp-content/uploads/2020/06/Stevenage-Logo.png"
  Northampton: "https://logos-world.net/wp-content/uploads/2020/06/Northampton-Town-Logo.png"
  Mansfield: "https://logos-world.net/wp-content/uploads/2020/06/Mansfield-Town-Logo.png"
  Crewe: "https://logos-world.net/wp-content/uploads/2020/06/Crewe-Alexandra-Logo.png"
  Grimsby: "https://logos-world.net/wp-content/uploads/2020/06/Grimsby-Town-Logo.png"
  Notts County: "https://logos-world.net/wp-content/uploads/2020/06/Notts-County-Logo.png"
  Wrexham: "https://logos-world.net/wp-content/uploads/2020/06/Wrexham-Logo.png"
  Stockport: "https://logos-world.net/wp-content/uploads/2020/06/Stockport-County-Logo.png"
  AFC Wimbledon: "https://logos-world.net/wp-content/uploads/2020/06/AFC-Wimbledon-Logo.png"
  Doncaster: "https://logos-world.net/wp-content/uploads/2020/06/Doncaster-Rovers-Logo.png"
  Bradford: "https://logos-world.net/wp-content/uploads/2020/06/Bradford-City-Logo.png"
  Salford: "https://logos-world.net/wp-content/uploads/2020/06/Salford-City-Logo.png"
  Tranmere: "https://logos-world.net/wp-content/uploads/2020/06/Tranmere-Rovers-Logo.png"
  Colchester: "https://logos-world.net/wp-content/uploads/2020/06/Colchester-United-Logo.png"
  Crawley: "https://logos-world.net/wp-content/uploads/2020/06/Crawley-Town-Logo.png"
  Harrogate: "https://logos-world.net/wp-content/uploads/2020/06/Harrogate-Town-Logo.png"
  Sutton: "https://logos-world.net/wp-content/uploads/2020/06/Sutton-United-Logo.png"
  Barrow: "https://logos-world.net/wp-content/uploads/2020/06/Barrow-Logo.png"
  Gillingham: "https://logos-world.net/wp-content/uploads/2020/06/Gillingham-Logo.png"
  Forest Green: "https://logos-world.net/wp-content/uploads/2020/06/Forest-Green-Rovers-Logo.png"
  Accrington: "https://logos-world.net/wp-content/uploads/2020/06/Accrington-Stanley-Logo.png"
  Morecambe: "https://logos-world.net/wp-content/uploads/2020/06/Morecambe-Logo.png"
  Walsall: "https://logos-world.net/wp-content/uploads/2020/06/Walsall-Logo.png"
  Newport: "https://logos-world.net/wp-content/uploads/2020/06/Newport-County-Logo.png"
  MK Dons: "https://logos-world.net/wp-content/uploads/2020/06/Milton-Keynes-Dons-Logo.png"
  Cheltenham: "https://logos-world.net/wp-content/uploads/2020/06/Cheltenham-Town-Logo.png"
  Swindon: "https://logos-world.net/wp-content/uploads/2020/06/Swindon-Town-Logo.png"
  Carlisle: "https://logos-world.net/wp-content/uploads/2020/06/Carlisle-United-Logo.png"
  Leyton Orient: "https://logos-world.net/wp-content/uploads/2020/06/Leyton-Orient-Logo.png"
  Rochdale: "https://logos-world.net/wp-content/uploads/2020/06/Rochdale-Logo.png"
  Hartlepool: "https://logos-world.net/wp-content/uploads/2020/06/Hartlepool-United-Logo.png"
  Scunthorpe: "https://logos-world.net/wp-content/uploads/2020/06/Scunthorpe-United-Logo.png"
  Oldham: "https://logos-world.net/wp-content/uploads/2020/06/Oldham-Athletic-Logo.png"
  Yeovil: "https://logos-world.net/wp-content/uploads/2020/06/Yeovil-Town-Logo.png"
  Barnet: "https://logos-world.net/wp-content/uploads/2020/06/Barnet-Logo.png"
  Boreham Wood: "https://logos-world.net/wp-content/uploads/2020/06/Boreham-Wood-Logo.png"
  Chesterfield: "https://logos-world.net/wp-content/uploads/2020/06/Chesterfield-Logo.png"
  Dagenham: "https://logos-world.net/wp-content/uploads/2020/06/Dagenham-Redbridge-Logo.png"
  Eastleigh: "https://logos-world.net/wp-content/uploads/2020/06/Eastleigh-Logo.png"
  Halifax: "https://logos-world.net/wp-content/uploads/2020/06/FC-Halifax-Town-Logo.png"
  Gateshead: "https://logos-world.net/wp-content/uploads/2020/06/Gateshead-Logo.png"
  Maidenhead: "https://logos-world.net/wp-content/uploads/2020/06/Maidenhead-United-Logo.png"
  Solihull: "https://logos-world.net/wp-content/uploads/2020/06/Solihull-Moors-Logo.png"
  Southend: "https://logos-world.net/wp-content/uploads/2020/06/Southend-United-Logo.png"
  Wealdstone: "https://logos-world.net/wp-content/uploads/2020/06/Wealdstone-Logo.png"
  Woking: "https://logos-world.net/wp-content/uploads/2020/06/Woking-Logo.png"
  York: "https://logos-world.net/wp-content/uploads/2020/06/York-City-Logo.png"
  Aldershot: "https://logos-world.net/wp-content/uploads/2020/06/Aldershot-Town-Logo.png"
  Altrincham: "https://logos-world.net/wp-content/uploads/2020/06/Altrincham-Logo.png"
  Barnet: "https://logos-world.net/wp-content/uploads/2020/06/Barnet-Logo.png"
  Bromley: "https://logos-world.net/wp-content/uploads/2020/06/Bromley-Logo.png"
  Chester: "https://logos-world.net/wp-content/uploads/2020/06/Chester-Logo.png"
  Dorking: "https://logos-world.net/wp-content/uploads/2020/06/Dorking-Wanderers-Logo.png"
  Ebbsfleet: "https://logos-world.net/wp-content/uploads/2020/06/Ebbsfleet-United-Logo.png"
  Fylde: "https://logos-world.net/wp-content/uploads/2020/06/AFC-Fylde-Logo.png"
  Hartlepool: "https://logos-world.net/wp-content/uploads/2020/06/Hartlepool-United-Logo.png"
  Kidderminster: "https://logos-world.net/wp-content/uploads/2020/06/Kidderminster-Harriers-Logo.png"
  Oldham: "https://logos-world.net/wp-content/uploads/2020/06/Oldham-Athletic-Logo.png"
  Oxford City: "https://logos-world.net/wp-content/uploads/2020/06/Oxford-City-Logo.png"
  Rochdale: "https://logos-world.net/wp-content/uploads/2020/06/Rochdale-Logo.png"
  Solihull Moors: "https://logos-world.net/wp-content/uploads/2020/06/Solihull-Moors-Logo.png"
  Southend United: "https://logos-world.net/wp-content/uploads/2020/06/Southend-United-Logo.png"
  Wealdstone: "https://logos-world.net/wp-content/uploads/2020/06/Wealdstone-Logo.png"
  Woking: "https://logos-world.net/wp-content/uploads/2020/06/Woking-Logo.png"
  York City: "https://logos-world.net/wp-content/uploads/2020/06/York-City-Logo.png"

la_liga:
  Real Madrid: "https://logos-world.net/wp-content/uploads/2020/06/Real-Madrid-Logo.png"
  Barcelona: "https://logos-world.net/wp-content/uploads/2020/06/Barcelona-Logo.png"
  Atletico Madrid: "https://logos-world.net/wp-content/uploads/2020/06/Atletico-Madrid-Logo.png"
  Sevilla: "https://logos-world.net/wp-content/uploads/2020/06/Sevilla-Logo.png"
  Valencia: "https://logos-world.net/wp-content/uploads/2020/06/Valencia-Logo.png"
  Villarreal: "https://logos-world.net/wp-content/uploads/2020/06/Villarreal-Logo.png"
  Real Sociedad: "https://logos-world.net/wp-content/uploads/2020/06/Real-Sociedad-Logo.png"
  Athletic Bilbao: "https://logos-world.net/wp-content/uploads/2020/06/Athletic-Bilbao-Logo.png"
  Real Betis: "https://logos-world.net/wp-content/uploads/2020/06/Real-Betis-Logo.png"
  Getafe: "https://logos-world.net/wp-content/uploads/2020/06/Getafe-Logo.png"
  Celta Vigo: "https://logos-world.net/wp-content/uploads/2020/06/Celta-Vigo-Logo.png"
  Espanyol: "https://logos-world.net/wp-content/uploads/2020/06/Espanyol-Logo.png"
  Granada: "https://logos-world.net/wp-content/uploads/2020/06/Granada-Logo.png"
  Levante: "https://logos-world.net/wp-content/uploads/2020/06/Levante-Logo.png"
  Mallorca: "https://logos-world.net/wp-content/uploads/2020/06/Mallorca-Logo.png"
  Osasuna: "https://logos-world.net/wp-content/uploads/2020/06/Osasuna-Logo.png"
  Rayo Vallecano: "https://logos-world.net/wp-content/uploads/2020/06/Rayo-Vallecano-Logo.png"
  Real Madrid: "https://logos-world.net/wp-content/uploads/2020/06/Real-Madrid-Logo.png"
  Cadiz: "https://logos-world.net/wp-content/uploads/2020/06/Cadiz-Logo.png"
  Alaves: "https://logos-world.net/wp-content/uploads/2020/06/Alaves-Logo.png"

bundesliga:
  Bayern Munich: "https://logos-world.net/wp-content/uploads/2020/06/Bayern-Munich-Logo.png"
  Borussia Dortmund: "https://logos-world.net/wp-content/uploads/2020/06/Borussia-Dortmund-Logo.png"
  RB Leipzig: "https://logos-world.net/wp-content/uploads/2020/06/RB-Leipzig-Logo.png"
  Bayer Leverkusen: "https://logos-world.net/wp-content/uploads/2020/06/Bayer-Leverkusen-Logo.png"
  Eintracht Frankfurt: "https://logos-world.net/wp-content/uploads/2020/06/Eintracht-Frankfurt-Logo.png"
  Borussia M.Gladbach: "https://logos-world.net/wp-content/uploads/2020/06/Borussia-Monchengladbach-Logo.png"
  Wolfsburg: "https://logos-world.net/wp-content/uploads/2020/06/Wolfsburg-Logo.png"
  Union Berlin: "https://logos-world.net/wp-content/uploads/2020/06/Union-Berlin-Logo.png"
  Freiburg: "https://logos-world.net/wp-content/uploads/2020/06/Freiburg-Logo.png"
  Hoffenheim: "https://logos-world.net/wp-content/uploads/2020/06/Hoffenheim-Logo.png"
  Mainz: "https://logos-world.net/wp-content/uploads/2020/06/Mainz-Logo.png"
  Augsburg: "https://logos-world.net/wp-content/uploads/2020/06/Augsburg-Logo.png"
  Hertha Berlin: "https://logos-world.net/wp-content/uploads/2020/06/Hertha-Berlin-Logo.png"
  Cologne: "https://logos-world.net/wp-content/uploads/2020/06/Cologne-Logo.png"
  Stuttgart: "https://logos-world.net/wp-content/uploads/2020/06/Stuttgart-Logo.png"
  Bochum: "https://logos-world.net/wp-content/uploads/2020/06/Bochum-Logo.png"
  Arminia Bielefeld: "https://logos-world.net/wp-content/uploads/2020/06/Arminia-Bielefeld-Logo.png"
  Greuther Furth: "https://logos-world.net/wp-content/uploads/2020/06/Greuther-Furth-Logo.png"

serie_a:
  Juventus: "https://logos-world.net/wp-content/uploads/2020/06/Juventus-Logo.png"
  Inter: "https://logos-world.net/wp-content/uploads/2020/06/Inter-Milan-Logo.png"
  AC Milan: "https://logos-world.net/wp-content/uploads/2020/06/AC-Milan-Logo.png"
  Napoli: "https://logos-world.net/wp-content/uploads/2020/06/Napoli-Logo.png"
  Roma: "https://logos-world.net/wp-content/uploads/2020/06/AS-Roma-Logo.png"
  Lazio: "https://logos-world.net/wp-content/uploads/2020/06/Lazio-Logo.png"
  Atalanta: "https://logos-world.net/wp-content/uploads/2020/06/Atalanta-Logo.png"
  Fiorentina: "https://logos-world.net/wp-content/uploads/2020/06/Fiorentina-Logo.png"
  Torino: "https://logos-world.net/wp-content/uploads/2020/06/Torino-Logo.png"
  Bologna: "https://logos-world.net/wp-content/uploads/2020/06/Bologna-Logo.png"
  Sampdoria: "https://logos-world.net/wp-content/uploads/2020/06/Sampdoria-Logo.png"
  Genoa: "https://logos-world.net/wp-content/uploads/2020/06/Genoa-Logo.png"
  Sassuolo: "https://logos-world.net/wp-content/uploads/2020/06/Sassuolo-Logo.png"
  Udinese: "https://logos-world.net/wp-content/uploads/2020/06/Udinese-Logo.png"
  Verona: "https://logos-world.net/wp-content/uploads/2020/06/Verona-Logo.png"
  Spezia: "https://logos-world.net/wp-content/uploads/2020/06/Spezia-Logo.png"
  Cagliari: "https://logos-world.net/wp-content/uploads/2020/06/Cagliari-Logo.png"
  Empoli: "https://logos-world.net/wp-content/uploads/2020/06/Empoli-Logo.png"
  Salernitana: "https://logos-world.net/wp-content/uploads/2020/06/Salernitana-Logo.png"
  Venezia: "https://logos-world.net/wp-content/uploads/2020/06/Venezia-Logo.png"

ligue_1:
  PSG: "https://logos-world.net/wp-content/uploads/2020/06/Paris-Saint-Germain-Logo.png"
  Marseille: "https://logos-world.net/wp-content/uploads/2020/06/Marseille-Logo.png"
  Lyon: "https://logos-world.net/wp-content/uploads/2020/06/Lyon-Logo.png"
  Monaco: "https://logos-world.net/wp-content/uploads/2020/06/Monaco-Logo.png"
  Lille: "https://logos-world.net/wp-content/uploads/2020/06/Lille-Logo.png"
  Nice: "https://logos-world.net/wp-content/uploads/2020/06/Nice-Logo.png"
  Rennes: "https://logos-world.net/wp-content/uploads/2020/06/Rennes-Logo.png"
  Strasbourg: "https://logos-world.net/wp-content/uploads/2020/06/Strasbourg-Logo.png"
  Montpellier: "https://logos-world.net/wp-content/uploads/2020/06/Montpellier-Logo.png"
  Nantes: "https://logos-world.net/wp-content/uploads/2020/06/Nantes-Logo.png"
  Lens: "https://logos-world.net/wp-content/uploads/2020/06/Lens-Logo.png"
  Reims: "https://logos-world.net/wp-content/uploads/2020/06/Reims-Logo.png"
  Brest: "https://logos-world.net/wp-content/uploads/2020/06/Brest-Logo.png"
  Angers: "https://logos-world.net/wp-content/uploads/2020/06/Angers-Logo.png"
  Metz: "https://logos-world.net/wp-content/uploads/2020/06/Metz-Logo.png"
  Troyes: "https://logos-world.net/wp-content/uploads/2020/06/Troyes-Logo.png"
  Clermont: "https://logos-world.net/wp-content/uploads/2020/06/Clermont-Logo.png"
  Lorient: "https://logos-world.net/wp-content/uploads/2020/06/Lorient-Logo.png"
  Saint-Etienne: "https://logos-world.net/wp-content/uploads/2020/06/Saint-Etienne-Logo.png"
